"""empty message

Revision ID: 31123a71e593
Revises: e1eefb423922
Create Date: 2024-07-06 00:41:52.501216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31123a71e593'
down_revision = 'e1eefb423922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('time_in_shelter',
               existing_type=sa.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogs', schema=None) as batch_op:
        batch_op.alter_column('time_in_shelter',
               existing_type=sa.Integer(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
