"""empty message

Revision ID: 3a88783deba0
Revises: 31123a71e593
Create Date: 2024-07-06 01:12:00.408878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a88783deba0'
down_revision = '31123a71e593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adoption_fee', sa.Float(), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('adoption_fee')

    # ### end Alembic commands ###
