"""deleted column in adoption table

Revision ID: de14779f3c1e
Revises: 8177cef5a969
Create Date: 2024-07-08 16:59:38.323880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de14779f3c1e'
down_revision = '8177cef5a969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.drop_column('is_adopted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_adopted', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
